# true 1 和 false 0 
width: 1080           #图像宽度
height: 812            #图像高度
Offset_x: 0             #X方向偏置
Offset_y: 0             #Y方向偏置

FrameRateEnable: false   #使能
FrameRate: 60          #帧率

ExposureTime: 5000  #曝光时间

GammaEnable: true
Gamma: 0.7              #伽马因子

GainAuto: 2             #亮度的固定增益

SaturationEnable: false
Saturation: 128          #饱和度
